version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
  radar:
    build:
      context: .
      dockerfile: ./RadarModule/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
  camera:
    build:
      context: .
      dockerfile: ./CameraModule/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
  gpio:
    build: ./gpio
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/mem:/dev/mem"
      - "/dev/ttyACM0:/dev/ttyACM0"
    cap_add:
      - SYS_RAWIO