# Generated by Django 4.0.3 on 2022-04-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_changespeed_radarreading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangeSpeed',
            new_name='SpeedThreshhold',
        ),
        migrations.RenameField(
            model_name='speedthreshhold',
            old_name='speed',
            new_name='newSpeed',
        ),
    ]
